#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       non-POSIX, but you have a POSIX-compliant shell named $SHELL, set
#       GRADLE_USE_SHELL to point to it.
#
#   (2) If you want to use the Java version bundled with your JRE, set
#       GRADLE_JAVA_HOME to the path of the JRE.
#
#   (3) If you want to use a different version of the JDK, set JAVA_HOME to
#       the path of the JDK.
#
#   (4) Add this directory to your PATH to run gradlew from anywhere.
#
##############################################################################

# Attempt to set JAVA_HOME if it's not already set
if [ -z "$JAVA_HOME" ]; then
  if [ -x "$(command -v java)" ]; then
    JAVA_HOME="$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | awk '{print $3}')"
  fi
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx2G"'

APP_NAME="Gradle"
APP_BASE_NAME="$(basename "$0")"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="max"

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  Darwin* )
    darwin=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executable
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
else
    JAVACMD="java"
    if [ ! -x "$(command -v "$JAVACMD")" ] ; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
fi

# Increase the heap size for the Gradle daemon (if not already set)
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS"

# Collect all the arguments passed to the script
GRADLE_OPTS="$GRADLE_OPTS $DEFAULT_JVM_OPTS"
export GRADLE_OPTS

# Determine the directory where this script is located
PRG="$0"
# resolve symlinks
while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(echo "$ls" | awk '{print $NF}')
  if expr "$link" : "/" >/dev/null; then
    PRG="$link"
  else
    PRG="$(dirname "$PRG")/$link"
  fi
done
DIR=$(cd -P -- "$(dirname -- "$PRG")" && pwd -P)

# Build the classpath
CLASSPATH="$DIR/gradle/wrapper/gradle-wrapper.jar"
export CLASSPATH

# Setup the main class
MAIN_CLASS="org.gradle.wrapper.GradleWrapperMain"

# Setup the arguments
if [ "$darwin" = "true" ]; then
    # This is a mix between:
    # https://github.com/gradle/gradle/pull/14521/files#diff-2b97ac9cf911517ed908ffa20948ae7320a4614e097cf9d70f8f97efd753d009
    # and the old behavior
    OPTS="-Dorg.gradle.appname=$APP_BASE_NAME -classpath $CLASSPATH $MAIN_CLASS"
else
    OPTS="-Dorg.gradle.appname=$APP_BASE_NAME -classpath $CLASSPATH $MAIN_CLASS"
fi

# Exec the JVM with the appropriate arguments
exec "$JAVACMD" $GRADLE_OPTS $OPTS "$@"
